stages:
  train:
    cmd: python3 src/train.py data/texts/shakespeare.txt
    deps:
    - data/names/English.txt
    - src/train.py
    - src/model.py
    params:
    - train.learning_rate
    - train.batch_size
    - train.segment_length
    - train.iterations
    - train.report_every
    outs:
    - data/models/
    metrics:
    - scores.json:
        cache: false
    plots:
    - loss_curve.json:
        cache: false
        x: epoch
        y: loss
